config/routes.rb
Rails.application.routes.draw do

  root 'page#home'

  get 'page/home'
  get 'page/newsletter'

  resources :newsletters

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base

  validates_presence_of :name
  validates_format_of :email, :with =>  /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => "Please enter a valid email address"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: 'Newsletter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:name, :email)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def newsletter
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <ul>
    <li><%= link_to 'Home', page_home_path %> </li>
    <li><%= link_to 'About', "/page/home#thirdImage" %></li>
    <li> <%= link_to('Newsletter', page_newsletter_path) %></li>
  </ul>
</nav>

<%= yield %>

</body>
</html>

app/views/newsletters/_form.html.erb
<section id="fithImage">
  <div class="container">
    <div class="align">
      <%= form_for(@newsletter) do |f| %>
          <% if @newsletter.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

                <ul>
                  <% @newsletter.errors.full_messages.each do |message| %>
                      <li><%= message %></li>

                  <% end %>
                </ul>
              </div>
          <% end %>

          <fieldset>
            <legend>Newsletter</legend>

            <%= f.label :name %>
            <%= f.text_field :name %>


            <%= f.label :email %>
            <%= f.text_field :email %>


            <%= f.submit %>

          </fieldset>
      <% end %>

    </div>
  </div>
</section>

app/views/newsletters/edit.html.erb
<h1>Editing newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<h1>Listing newsletters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsletters.each do |newsletter| %>
      <tr>
        <td><%= newsletter.name %></td>
        <td><%= newsletter.email %></td>
        <td><%= link_to 'Show', newsletter %></td>
        <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
        <td><%= link_to 'Destroy', newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsletter', new_newsletter_path %>

app/views/newsletters/new.html.erb
<h1>New newsletter</h1>

<%= render 'form' %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @newsletter.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @newsletter.email %>
</p>

<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>

app/views/page/home.html.erb
<section id="mainImage">
  <div class="container">


    <div id="slideshow">
      <p> Joao Aguilera CS80</p>
      <%= image_tag("img1.png", size:"400x450", :class => "slide") %>
    </div>
  </div> <!-- container -->

</section> <!-- mainImage -->
<section id="secondImage">
  <div class="container">
    <div class="wordContent">
      <div class="center">
        <p>Exerci omittam mnesarchum eum ea, ullum inermis scaevola et
        </p>
      </div>
    </div>
  </div>
</section>

<section id="thirdImage">
  <div class="container">
    <div class="myText">
      <p>Lorem ipsum dolor sit amet, usu at euismod nominati iracundia. Vim malorum deserunt maluisset at, id quo ceteros phaedrum qualisque. Vis possim prompta facilis ei, quod odio ex qui, ex tempor fabellas dignissim per. Ne tollit graeco minimum est, ius et docendi facilisi phaedrum. Iisque volumus fabellas id mel, in sed clita incorrupte.
      </p>
      <p> Et nostrum disputationi interpretaris ius. Saperet volumus aliquando cum ne, sea cu tota principes, primis fabulas duo et. Duo dolor similique scriptorem eu, cu eum delenit habemus suscipit, te sed scribentur disputationi. Congue quaeque eos ei, cu eos tempor consetetur, ei pri nisl error albucius. Dolorum deleniti sed ea, ei audire adipiscing ius, fugit saepe periculis an vix.
      </p>
      <p>Exerci omittam mnesarchum eum ea, ullum inermis scaevola et his, utinam nostrud nostrum nam te. Velit impedit reprehendunt in vel, omnes doming singulis no mea. Option posidonium interesset per id. Ex noluisse necessitatibus per. Eam ex nihil minimum vivendum, wisi vivendum eloquentiam ne nec, te facete voluptua consequuntur eum. Te tibique torquatos scripserit mei, te vix pertinax eleifend.       </p>
      <p>Cu erant sadipscing sed, per soluta discere cu. In etiam perfecto definiebas nec, luptatum dissentiunt eu qui. Sea mentitum intellegat consequuntur ne, vero mollis in sit. Eos cu tamquam adversarium signiferumque. Bonorum oporteat intellegat ne vix, qui mucius possit torquatos at, solet legimus id vel.
      </p>
      <p>	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      <p>Exerci omittam mnesarchum eum ea, ullum inermis scaevola et his, utinam nostrud nostrum nam te. Velit impedit reprehendunt in vel, omnes doming singulis no mea. Option posidonium interesset per id. Ex noluisse necessitatibus per. Eam ex nihil minimum vivendum, wisi vivendum eloquentiam ne nec, te facete voluptua consequuntur eum. Te tibique torquatos scripserit mei, te vix pertinax eleifend.       </p>
      <p> Et nostrum disputationi interpretaris ius. Saperet volumus aliquando cum ne, sea cu tota principes, primis fabulas duo et. Duo dolor similique scriptorem eu, cu eum delenit habemus suscipit, te sed scribentur disputationi. Congue quaeque eos ei, cu eos tempor consetetur, ei pri nisl error albucius. Dolorum deleniti sed e
      </p>
      <p>Exerci omittam mnesarchum eum ea, ullum inermis scaevola et his, utinam nostrud nostrum nam te. Velit impedit reprehendunt in vel, omnes doming singulis no mea. Option posidonium interesset per id. Ex noluisse necessitatibus per. Eam ex nihil minimum vivendum, wisi vivendum eloquentiam ne nec, te facete voluptua consequuntur eum. Te tibique torquatos scripserit mei, te vix pertinax eleifend.       </p>
      <p>Cu erant sadipscing sed, per soluta discere cu. In etiam perfecto definiebas nec, luptatum dissentiunt eu qui. Sea mentitum intellegat consequuntur ne, vero mollis in sit. Eos cu tamquam adversarium signiferumque. Bonorum oporteat intellegat ne vix, qui mucius possit torquatos at, solet legimus id vel.
      </p>

    </div>
  </div>
</section>

<section id="fourthImage">
  <div class="container">
    <div class="center">
      <p class="myPcenter"> Stay Informed!</p>

      <%= button_to "Sign Up", page_newsletter_path, class:"myButton" ,:method => "get"%>

    </div>
  </div>
</section>

app/views/page/newsletter.html.erb
<section id="fithImage">
  <div class="container">
    <div class="align">
      <!-- action and extra form information is not included because I don't want the information to be sent -->
      <form>
        <fieldset>
          <legend>Newsletter</legend>
          <label for="name">Name:</label>
          <input type="text" id="name">
          <label for="email">Email:</label>
          <input type="text" id="email">
          <input type="submit" value="subscribe" id="sumbit">
        </fieldset>
      </form>
    </div>
  </div>
</section>